//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 
namespace BGGAPI.Schemas.Collection {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class items {
        
        private collectionItemType[] itemField;
        
        private int totalitemsField;
        
        private bool totalitemsFieldSpecified;
        
        private string termsofuseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("item")]
        public collectionItemType[] item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int totalitems {
            get {
                return this.totalitemsField;
            }
            set {
                this.totalitemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalitemsSpecified {
            get {
                return this.totalitemsFieldSpecified;
            }
            set {
                this.totalitemsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string termsofuse {
            get {
                return this.termsofuseField;
            }
            set {
                this.termsofuseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class collectionItemType {
        
        private sortType nameField;
        
        private string originalnameField;
        
        private string yearpublishedField;
        
        private string imageField;
        
        private string thumbnailField;
        
        private statsType statsField;
        
        private collectionItemTypeStatus statusField;
        
        private int numplaysField;
        
        private bool numplaysFieldSpecified;
        
        private collectionItemTypeVersion versionField;
        
        private string objecttypeField;
        
        private int objectidField;
        
        private bool objectidFieldSpecified;
        
        private string subtypeField;
        
        private int collidField;
        
        private bool collidFieldSpecified;
        
        /// <remarks/>
        public sortType name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string originalname {
            get {
                return this.originalnameField;
            }
            set {
                this.originalnameField = value;
            }
        }
        
        /// <remarks/>
        public string yearpublished {
            get {
                return this.yearpublishedField;
            }
            set {
                this.yearpublishedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string thumbnail {
            get {
                return this.thumbnailField;
            }
            set {
                this.thumbnailField = value;
            }
        }
        
        /// <remarks/>
        public statsType stats {
            get {
                return this.statsField;
            }
            set {
                this.statsField = value;
            }
        }
        
        /// <remarks/>
        public collectionItemTypeStatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public int numplays {
            get {
                return this.numplaysField;
            }
            set {
                this.numplaysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numplaysSpecified {
            get {
                return this.numplaysFieldSpecified;
            }
            set {
                this.numplaysFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public collectionItemTypeVersion version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string objecttype {
            get {
                return this.objecttypeField;
            }
            set {
                this.objecttypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int objectid {
            get {
                return this.objectidField;
            }
            set {
                this.objectidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool objectidSpecified {
            get {
                return this.objectidFieldSpecified;
            }
            set {
                this.objectidFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string subtype {
            get {
                return this.subtypeField;
            }
            set {
                this.subtypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int collid {
            get {
                return this.collidField;
            }
            set {
                this.collidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool collidSpecified {
            get {
                return this.collidFieldSpecified;
            }
            set {
                this.collidFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sortType {
        
        private int sortindexField;
        
        private bool sortindexFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int sortindex {
            get {
                return this.sortindexField;
            }
            set {
                this.sortindexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sortindexSpecified {
            get {
                return this.sortindexFieldSpecified;
            }
            set {
                this.sortindexFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class linkType {
        
        private string typeField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string valueField;
        
        private string inboundField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string inbound {
            get {
                return this.inboundField;
            }
            set {
                this.inboundField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class stringValueType {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nameType {
        
        private string typeField;
        
        private int sortindexField;
        
        private bool sortindexFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int sortindex {
            get {
                return this.sortindexField;
            }
            set {
                this.sortindexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sortindexSpecified {
            get {
                return this.sortindexFieldSpecified;
            }
            set {
                this.sortindexFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class versionItemType {
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        private string typeField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("depth", typeof(decimalValueType))]
        [System.Xml.Serialization.XmlElementAttribute("image", typeof(string), DataType="anyURI")]
        [System.Xml.Serialization.XmlElementAttribute("length", typeof(decimalValueType))]
        [System.Xml.Serialization.XmlElementAttribute("link", typeof(linkType))]
        [System.Xml.Serialization.XmlElementAttribute("name", typeof(nameType))]
        [System.Xml.Serialization.XmlElementAttribute("productcode", typeof(stringValueType))]
        [System.Xml.Serialization.XmlElementAttribute("thumbnail", typeof(string), DataType="anyURI")]
        [System.Xml.Serialization.XmlElementAttribute("weight", typeof(decimalValueType))]
        [System.Xml.Serialization.XmlElementAttribute("width", typeof(decimalValueType))]
        [System.Xml.Serialization.XmlElementAttribute("yearpublished", typeof(stringValueType))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class decimalValueType {
        
        private decimal valueField;
        
        private bool valueFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueSpecified {
            get {
                return this.valueFieldSpecified;
            }
            set {
                this.valueFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        depth,
        
        /// <remarks/>
        image,
        
        /// <remarks/>
        length,
        
        /// <remarks/>
        link,
        
        /// <remarks/>
        name,
        
        /// <remarks/>
        productcode,
        
        /// <remarks/>
        thumbnail,
        
        /// <remarks/>
        weight,
        
        /// <remarks/>
        width,
        
        /// <remarks/>
        yearpublished,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class integerValueType {
        
        private int valueField;
        
        private bool valueFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueSpecified {
            get {
                return this.valueFieldSpecified;
            }
            set {
                this.valueFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ratingsType {
        
        private integerValueType usersratedField;
        
        private decimalValueType averageField;
        
        private decimalValueType bayesaverageField;
        
        private decimalValueType stddevField;
        
        private decimalValueType medianField;
        
        private ratingsTypeRank[] ranksField;
        
        private int valueField;
        
        private bool valueFieldSpecified;
        
        /// <remarks/>
        public integerValueType usersrated {
            get {
                return this.usersratedField;
            }
            set {
                this.usersratedField = value;
            }
        }
        
        /// <remarks/>
        public decimalValueType average {
            get {
                return this.averageField;
            }
            set {
                this.averageField = value;
            }
        }
        
        /// <remarks/>
        public decimalValueType bayesaverage {
            get {
                return this.bayesaverageField;
            }
            set {
                this.bayesaverageField = value;
            }
        }
        
        /// <remarks/>
        public decimalValueType stddev {
            get {
                return this.stddevField;
            }
            set {
                this.stddevField = value;
            }
        }
        
        /// <remarks/>
        public decimalValueType median {
            get {
                return this.medianField;
            }
            set {
                this.medianField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("rank", IsNullable=false)]
        public ratingsTypeRank[] ranks {
            get {
                return this.ranksField;
            }
            set {
                this.ranksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueSpecified {
            get {
                return this.valueFieldSpecified;
            }
            set {
                this.valueFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ratingsTypeRank {
        
        private string typeField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string nameField;
        
        private string friendlynameField;
        
        private string valueField;
        
        private string bayesaverageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string friendlyname {
            get {
                return this.friendlynameField;
            }
            set {
                this.friendlynameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string bayesaverage {
            get {
                return this.bayesaverageField;
            }
            set {
                this.bayesaverageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class statsType {
        
        private ratingsType ratingField;
        
        private int minplayersField;
        
        private bool minplayersFieldSpecified;
        
        private int maxplayersField;
        
        private bool maxplayersFieldSpecified;
        
        private int playingtimeField;
        
        private bool playingtimeFieldSpecified;
        
        private int numownedField;
        
        private bool numownedFieldSpecified;
        
        /// <remarks/>
        public ratingsType rating {
            get {
                return this.ratingField;
            }
            set {
                this.ratingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int minplayers {
            get {
                return this.minplayersField;
            }
            set {
                this.minplayersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool minplayersSpecified {
            get {
                return this.minplayersFieldSpecified;
            }
            set {
                this.minplayersFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int maxplayers {
            get {
                return this.maxplayersField;
            }
            set {
                this.maxplayersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxplayersSpecified {
            get {
                return this.maxplayersFieldSpecified;
            }
            set {
                this.maxplayersFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int playingtime {
            get {
                return this.playingtimeField;
            }
            set {
                this.playingtimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool playingtimeSpecified {
            get {
                return this.playingtimeFieldSpecified;
            }
            set {
                this.playingtimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int numowned {
            get {
                return this.numownedField;
            }
            set {
                this.numownedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numownedSpecified {
            get {
                return this.numownedFieldSpecified;
            }
            set {
                this.numownedFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class collectionItemTypeStatus {
        
        private int ownField;
        
        private bool ownFieldSpecified;
        
        private int prevownedField;
        
        private bool prevownedFieldSpecified;
        
        private int fortradeField;
        
        private bool fortradeFieldSpecified;
        
        private int wantField;
        
        private bool wantFieldSpecified;
        
        private int wanttoplayField;
        
        private bool wanttoplayFieldSpecified;
        
        private int wanttobuyField;
        
        private bool wanttobuyFieldSpecified;
        
        private int wishlistField;
        
        private bool wishlistFieldSpecified;
        
        private int preorderedField;
        
        private bool preorderedFieldSpecified;
        
        private string lastmodifiedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int own {
            get {
                return this.ownField;
            }
            set {
                this.ownField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ownSpecified {
            get {
                return this.ownFieldSpecified;
            }
            set {
                this.ownFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int prevowned {
            get {
                return this.prevownedField;
            }
            set {
                this.prevownedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool prevownedSpecified {
            get {
                return this.prevownedFieldSpecified;
            }
            set {
                this.prevownedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int fortrade {
            get {
                return this.fortradeField;
            }
            set {
                this.fortradeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fortradeSpecified {
            get {
                return this.fortradeFieldSpecified;
            }
            set {
                this.fortradeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int want {
            get {
                return this.wantField;
            }
            set {
                this.wantField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool wantSpecified {
            get {
                return this.wantFieldSpecified;
            }
            set {
                this.wantFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int wanttoplay {
            get {
                return this.wanttoplayField;
            }
            set {
                this.wanttoplayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool wanttoplaySpecified {
            get {
                return this.wanttoplayFieldSpecified;
            }
            set {
                this.wanttoplayFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int wanttobuy {
            get {
                return this.wanttobuyField;
            }
            set {
                this.wanttobuyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool wanttobuySpecified {
            get {
                return this.wanttobuyFieldSpecified;
            }
            set {
                this.wanttobuyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int wishlist {
            get {
                return this.wishlistField;
            }
            set {
                this.wishlistField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool wishlistSpecified {
            get {
                return this.wishlistFieldSpecified;
            }
            set {
                this.wishlistFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int preordered {
            get {
                return this.preorderedField;
            }
            set {
                this.preorderedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool preorderedSpecified {
            get {
                return this.preorderedFieldSpecified;
            }
            set {
                this.preorderedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string lastmodified {
            get {
                return this.lastmodifiedField;
            }
            set {
                this.lastmodifiedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class collectionItemTypeVersion {
        
        private versionItemType itemField;
        
        /// <remarks/>
        public versionItemType item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
}
